import Header from '@/components/Header'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Contact from '@/components/Contact'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import './globals.css'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by hussain',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
      <body>
        <Header/>
        <About/>
        <Projects/>
        <Contact/>
        <ToastContainer/>
        {/* {children} */}
        
        </body>
      </>
    </html>
  )
}
